plugins {
    id 'com.android.application'
}

android {
    namespace 'pro.galaxyai.fold7'
    compileSdk 35

    defaultConfig {
        applicationId 'pro.galaxyai.fold7'
        minSdk 26
        targetSdk 35
        versionCode 440
        versionName '44.0'
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }
}
